//protoc --go_out=. --go-grpc_out=. push.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: push.proto

package push

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PushService_PushMsg_FullMethodName      = "/push.PushService/PushMsg"
	PushService_BatchPushMsg_FullMethodName = "/push.PushService/BatchPushMsg"
	PushService_CloseConn_FullMethodName    = "/push.PushService/CloseConn"
)

// PushServiceClient is the client API for PushService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PushService 消息推送服务
type PushServiceClient interface {
	// PushMsg 推送消息
	PushMsg(ctx context.Context, in *PushReq, opts ...grpc.CallOption) (*PushResp, error)
	// BatchPushMsg 批量推送消息
	BatchPushMsg(ctx context.Context, in *BatchPushReq, opts ...grpc.CallOption) (*BatchPushResp, error)
	// CloseConn 取消连接
	CloseConn(ctx context.Context, in *CloseConnReq, opts ...grpc.CallOption) (*CloseConnResp, error)
}

type pushServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPushServiceClient(cc grpc.ClientConnInterface) PushServiceClient {
	return &pushServiceClient{cc}
}

func (c *pushServiceClient) PushMsg(ctx context.Context, in *PushReq, opts ...grpc.CallOption) (*PushResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushResp)
	err := c.cc.Invoke(ctx, PushService_PushMsg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushServiceClient) BatchPushMsg(ctx context.Context, in *BatchPushReq, opts ...grpc.CallOption) (*BatchPushResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchPushResp)
	err := c.cc.Invoke(ctx, PushService_BatchPushMsg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushServiceClient) CloseConn(ctx context.Context, in *CloseConnReq, opts ...grpc.CallOption) (*CloseConnResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseConnResp)
	err := c.cc.Invoke(ctx, PushService_CloseConn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushServiceServer is the server API for PushService service.
// All implementations must embed UnimplementedPushServiceServer
// for forward compatibility.
//
// PushService 消息推送服务
type PushServiceServer interface {
	// PushMsg 推送消息
	PushMsg(context.Context, *PushReq) (*PushResp, error)
	// BatchPushMsg 批量推送消息
	BatchPushMsg(context.Context, *BatchPushReq) (*BatchPushResp, error)
	// CloseConn 取消连接
	CloseConn(context.Context, *CloseConnReq) (*CloseConnResp, error)
	mustEmbedUnimplementedPushServiceServer()
}

// UnimplementedPushServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPushServiceServer struct{}

func (UnimplementedPushServiceServer) PushMsg(context.Context, *PushReq) (*PushResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushMsg not implemented")
}
func (UnimplementedPushServiceServer) BatchPushMsg(context.Context, *BatchPushReq) (*BatchPushResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchPushMsg not implemented")
}
func (UnimplementedPushServiceServer) CloseConn(context.Context, *CloseConnReq) (*CloseConnResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseConn not implemented")
}
func (UnimplementedPushServiceServer) mustEmbedUnimplementedPushServiceServer() {}
func (UnimplementedPushServiceServer) testEmbeddedByValue()                     {}

// UnsafePushServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushServiceServer will
// result in compilation errors.
type UnsafePushServiceServer interface {
	mustEmbedUnimplementedPushServiceServer()
}

func RegisterPushServiceServer(s grpc.ServiceRegistrar, srv PushServiceServer) {
	// If the following call pancis, it indicates UnimplementedPushServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PushService_ServiceDesc, srv)
}

func _PushService_PushMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).PushMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_PushMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).PushMsg(ctx, req.(*PushReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_BatchPushMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPushReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).BatchPushMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_BatchPushMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).BatchPushMsg(ctx, req.(*BatchPushReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_CloseConn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseConnReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).CloseConn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_CloseConn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).CloseConn(ctx, req.(*CloseConnReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PushService_ServiceDesc is the grpc.ServiceDesc for PushService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PushService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "push.PushService",
	HandlerType: (*PushServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushMsg",
			Handler:    _PushService_PushMsg_Handler,
		},
		{
			MethodName: "BatchPushMsg",
			Handler:    _PushService_BatchPushMsg_Handler,
		},
		{
			MethodName: "CloseConn",
			Handler:    _PushService_CloseConn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "push.proto",
}
