//protoc --go_out=. --go-grpc_out=. message.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: idl/message/message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType 消息类型
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNkNOW       MessageType = 0 // 未知类型
	MessageType_MESSAGE_TYPE_CHAT         MessageType = 1 // 单聊消息
	MessageType_MESSAGE_TYPE_GROUP_CHAT   MessageType = 2 // 群聊消息
	MessageType_MESSAGE_TYPE_READ_RECEIPT MessageType = 3 // 已读回执消息
	MessageType_MESSAGE_TYPE_RECALL       MessageType = 4 // 撤回消息
	MessageType_MESSAGE_TYPE_DELETE       MessageType = 5 // 删除消息
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNkNOW",
		1: "MESSAGE_TYPE_CHAT",
		2: "MESSAGE_TYPE_GROUP_CHAT",
		3: "MESSAGE_TYPE_READ_RECEIPT",
		4: "MESSAGE_TYPE_RECALL",
		5: "MESSAGE_TYPE_DELETE",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNkNOW":       0,
		"MESSAGE_TYPE_CHAT":         1,
		"MESSAGE_TYPE_GROUP_CHAT":   2,
		"MESSAGE_TYPE_READ_RECEIPT": 3,
		"MESSAGE_TYPE_RECALL":       4,
		"MESSAGE_TYPE_DELETE":       5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_idl_message_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_idl_message_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_idl_message_message_proto_rawDescGZIP(), []int{0}
}

// MessageContentType 消息内容类型
type MessageElementType int32

const (
	MessageElementType_CONTENT_ELEMENT_UNKNOWN MessageElementType = 0 // 未知类型
	MessageElementType_CONTENT_ELEMENT_TEXT    MessageElementType = 1 // 文本消息
	MessageElementType_CONTENT_ELEMENT_IMAGE   MessageElementType = 2 // 图片消息
	MessageElementType_CONTENT_ELEMENT_VIDEO   MessageElementType = 3 // 视频消息
	MessageElementType_CONTENT_ELEMENT_FILE    MessageElementType = 4 // 文件消息
	MessageElementType_CONTENT_ELEMENT_AUDIO   MessageElementType = 5 // 音频消息
	MessageElementType_CONTENT_ELEMENT_STICKER MessageElementType = 6 // 表情包消息
	MessageElementType_CONTENT_ELEMENT_MENTION MessageElementType = 7 // @提醒元素（独立@元素）
	MessageElementType_CONTENT_ELEMENT_CUSTOM  MessageElementType = 8 // 自定义消息
)

// Enum value maps for MessageElementType.
var (
	MessageElementType_name = map[int32]string{
		0: "CONTENT_ELEMENT_UNKNOWN",
		1: "CONTENT_ELEMENT_TEXT",
		2: "CONTENT_ELEMENT_IMAGE",
		3: "CONTENT_ELEMENT_VIDEO",
		4: "CONTENT_ELEMENT_FILE",
		5: "CONTENT_ELEMENT_AUDIO",
		6: "CONTENT_ELEMENT_STICKER",
		7: "CONTENT_ELEMENT_MENTION",
		8: "CONTENT_ELEMENT_CUSTOM",
	}
	MessageElementType_value = map[string]int32{
		"CONTENT_ELEMENT_UNKNOWN": 0,
		"CONTENT_ELEMENT_TEXT":    1,
		"CONTENT_ELEMENT_IMAGE":   2,
		"CONTENT_ELEMENT_VIDEO":   3,
		"CONTENT_ELEMENT_FILE":    4,
		"CONTENT_ELEMENT_AUDIO":   5,
		"CONTENT_ELEMENT_STICKER": 6,
		"CONTENT_ELEMENT_MENTION": 7,
		"CONTENT_ELEMENT_CUSTOM":  8,
	}
)

func (x MessageElementType) Enum() *MessageElementType {
	p := new(MessageElementType)
	*p = x
	return p
}

func (x MessageElementType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageElementType) Descriptor() protoreflect.EnumDescriptor {
	return file_idl_message_message_proto_enumTypes[1].Descriptor()
}

func (MessageElementType) Type() protoreflect.EnumType {
	return &file_idl_message_message_proto_enumTypes[1]
}

func (x MessageElementType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageElementType.Descriptor instead.
func (MessageElementType) EnumDescriptor() ([]byte, []int) {
	return file_idl_message_message_proto_rawDescGZIP(), []int{1}
}

// UpstreamRequest 消息上行请求
type UpstreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// msg_type 消息类型（枚举）
	MsgType MessageType `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=message.MessageType" json:"msg_type,omitempty"`
	// payload 消息内容（字节数组）
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *UpstreamRequest) Reset() {
	*x = UpstreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_message_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpstreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamRequest) ProtoMessage() {}

func (x *UpstreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_message_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamRequest.ProtoReflect.Descriptor instead.
func (*UpstreamRequest) Descriptor() ([]byte, []int) {
	return file_idl_message_message_proto_rawDescGZIP(), []int{0}
}

func (x *UpstreamRequest) GetMsgType() MessageType {
	if x != nil {
		return x.MsgType
	}
	return MessageType_MESSAGE_TYPE_UNkNOW
}

func (x *UpstreamRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// UpstreamResponse 消息上行响应
type UpstreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// code 响应状态码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// message 响应消息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// UpstreamResult 结果数据
	Data *UpstreamResult `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpstreamResponse) Reset() {
	*x = UpstreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_message_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpstreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamResponse) ProtoMessage() {}

func (x *UpstreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_message_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamResponse.ProtoReflect.Descriptor instead.
func (*UpstreamResponse) Descriptor() ([]byte, []int) {
	return file_idl_message_message_proto_rawDescGZIP(), []int{1}
}

func (x *UpstreamResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpstreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpstreamResponse) GetData() *UpstreamResult {
	if x != nil {
		return x.Data
	}
	return nil
}

// UpstreamResult 结果数据
type UpstreamResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// msg_id 消息ID（客户端生成的msg_id）
	MsgId int64 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
}

func (x *UpstreamResult) Reset() {
	*x = UpstreamResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_message_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpstreamResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamResult) ProtoMessage() {}

func (x *UpstreamResult) ProtoReflect() protoreflect.Message {
	mi := &file_idl_message_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamResult.ProtoReflect.Descriptor instead.
func (*UpstreamResult) Descriptor() ([]byte, []int) {
	return file_idl_message_message_proto_rawDescGZIP(), []int{2}
}

func (x *UpstreamResult) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

// Message 消息体
type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// cli_msg_id 客户端消息ID
	CliMsgId int64 `protobuf:"varint,1,opt,name=cli_msg_id,json=cliMsgId,proto3" json:"cli_msg_id,omitempty"`
	// cli_seq_id 客户端消息序列ID
	CliSeqId int64 `protobuf:"varint,2,opt,name=cli_seq_id,json=cliSeqId,proto3" json:"cli_seq_id,omitempty"`
	// sender_id 发送者用户ID
	SenderId int64 `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// receiver_id 接收者用户ID(单聊)
	ReceiverId int64 `protobuf:"varint,4,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	// group_id 接收者群ID（群聊）
	GroupId int64 `protobuf:"varint,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// conversation_id 会话ID
	ConversationId int64 `protobuf:"varint,6,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// msg_type 消息类型（枚举）
	MsgType MessageType `protobuf:"varint,7,opt,name=msg_type,json=msgType,proto3,enum=message.MessageType" json:"msg_type,omitempty"`
	// msg_body 消息内容
	MsgBody []*MessageContent `protobuf:"bytes,8,rep,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	// sent_ts 客户端发送时间戳
	SentTs int64 `protobuf:"varint,9,opt,name=sent_ts,json=sentTs,proto3" json:"sent_ts,omitempty"`
	// at_users @的用户ID列表（可选，用于@提醒功能）
	AtUsers []int64 `protobuf:"varint,10,rep,packed,name=at_users,json=atUsers,proto3" json:"at_users,omitempty"`
	// at_all 是否@所有人（群聊时有效，true表示@所有人）
	AtAll bool `protobuf:"varint,11,opt,name=at_all,json=atAll,proto3" json:"at_all,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_message_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_idl_message_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_idl_message_message_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetCliMsgId() int64 {
	if x != nil {
		return x.CliMsgId
	}
	return 0
}

func (x *Message) GetCliSeqId() int64 {
	if x != nil {
		return x.CliSeqId
	}
	return 0
}

func (x *Message) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Message) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *Message) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *Message) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *Message) GetMsgType() MessageType {
	if x != nil {
		return x.MsgType
	}
	return MessageType_MESSAGE_TYPE_UNkNOW
}

func (x *Message) GetMsgBody() []*MessageContent {
	if x != nil {
		return x.MsgBody
	}
	return nil
}

func (x *Message) GetSentTs() int64 {
	if x != nil {
		return x.SentTs
	}
	return 0
}

func (x *Message) GetAtUsers() []int64 {
	if x != nil {
		return x.AtUsers
	}
	return nil
}

func (x *Message) GetAtAll() bool {
	if x != nil {
		return x.AtAll
	}
	return false
}

type MessageContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// element_type 消息内容类型（枚举，用于快速判断和兼容）
	ElementType MessageElementType `protobuf:"varint,1,opt,name=element_type,json=elementType,proto3,enum=message.MessageElementType" json:"element_type,omitempty"`
	// content 消息内容（使用oneof实现类型安全，支持复合消息）
	//
	// Types that are assignable to Content:
	//
	//	*MessageContent_Text
	//	*MessageContent_Image
	//	*MessageContent_Video
	//	*MessageContent_FileC
	//	*MessageContent_Audio
	//	*MessageContent_Sticker
	//	*MessageContent_Mention
	//	*MessageContent_Custom
	Content isMessageContent_Content `protobuf_oneof:"content"`
}

func (x *MessageContent) Reset() {
	*x = MessageContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_message_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContent) ProtoMessage() {}

func (x *MessageContent) ProtoReflect() protoreflect.Message {
	mi := &file_idl_message_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContent.ProtoReflect.Descriptor instead.
func (*MessageContent) Descriptor() ([]byte, []int) {
	return file_idl_message_message_proto_rawDescGZIP(), []int{4}
}

func (x *MessageContent) GetElementType() MessageElementType {
	if x != nil {
		return x.ElementType
	}
	return MessageElementType_CONTENT_ELEMENT_UNKNOWN
}

func (m *MessageContent) GetContent() isMessageContent_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *MessageContent) GetText() *TextElement {
	if x, ok := x.GetContent().(*MessageContent_Text); ok {
		return x.Text
	}
	return nil
}

func (x *MessageContent) GetImage() *ImageElement {
	if x, ok := x.GetContent().(*MessageContent_Image); ok {
		return x.Image
	}
	return nil
}

func (x *MessageContent) GetVideo() *VideoElement {
	if x, ok := x.GetContent().(*MessageContent_Video); ok {
		return x.Video
	}
	return nil
}

func (x *MessageContent) GetFileC() *FileElement {
	if x, ok := x.GetContent().(*MessageContent_FileC); ok {
		return x.FileC
	}
	return nil
}

func (x *MessageContent) GetAudio() *AudioElement {
	if x, ok := x.GetContent().(*MessageContent_Audio); ok {
		return x.Audio
	}
	return nil
}

func (x *MessageContent) GetSticker() *StickerElement {
	if x, ok := x.GetContent().(*MessageContent_Sticker); ok {
		return x.Sticker
	}
	return nil
}

func (x *MessageContent) GetMention() *MentionElement {
	if x, ok := x.GetContent().(*MessageContent_Mention); ok {
		return x.Mention
	}
	return nil
}

func (x *MessageContent) GetCustom() *CustomElement {
	if x, ok := x.GetContent().(*MessageContent_Custom); ok {
		return x.Custom
	}
	return nil
}

type isMessageContent_Content interface {
	isMessageContent_Content()
}

type MessageContent_Text struct {
	Text *TextElement `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type MessageContent_Image struct {
	Image *ImageElement `protobuf:"bytes,3,opt,name=image,proto3,oneof"`
}

type MessageContent_Video struct {
	Video *VideoElement `protobuf:"bytes,4,opt,name=video,proto3,oneof"`
}

type MessageContent_FileC struct {
	FileC *FileElement `protobuf:"bytes,5,opt,name=file_c,json=fileC,proto3,oneof"`
}

type MessageContent_Audio struct {
	Audio *AudioElement `protobuf:"bytes,6,opt,name=audio,proto3,oneof"`
}

type MessageContent_Sticker struct {
	Sticker *StickerElement `protobuf:"bytes,7,opt,name=sticker,proto3,oneof"`
}

type MessageContent_Mention struct {
	Mention *MentionElement `protobuf:"bytes,8,opt,name=mention,proto3,oneof"` // @提醒元素
}

type MessageContent_Custom struct {
	Custom *CustomElement `protobuf:"bytes,9,opt,name=custom,proto3,oneof"`
}

func (*MessageContent_Text) isMessageContent_Content() {}

func (*MessageContent_Image) isMessageContent_Content() {}

func (*MessageContent_Video) isMessageContent_Content() {}

func (*MessageContent_FileC) isMessageContent_Content() {}

func (*MessageContent_Audio) isMessageContent_Content() {}

func (*MessageContent_Sticker) isMessageContent_Content() {}

func (*MessageContent_Mention) isMessageContent_Content() {}

func (*MessageContent_Custom) isMessageContent_Content() {}

// TextElement 文本消息内容
type TextElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// text 文本内容
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TextElement) Reset() {
	*x = TextElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_message_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextElement) ProtoMessage() {}

func (x *TextElement) ProtoReflect() protoreflect.Message {
	mi := &file_idl_message_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextElement.ProtoReflect.Descriptor instead.
func (*TextElement) Descriptor() ([]byte, []int) {
	return file_idl_message_message_proto_rawDescGZIP(), []int{5}
}

func (x *TextElement) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// ImageElement 图片消息内容
type ImageElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// url 图片URL
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// width 图片宽度
	Width int32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	// height 图片高度
	Height int32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	// size 图片大小（字节数）
	Size int64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// uuid 图片唯一标识符
	Uuid string `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *ImageElement) Reset() {
	*x = ImageElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_message_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageElement) ProtoMessage() {}

func (x *ImageElement) ProtoReflect() protoreflect.Message {
	mi := &file_idl_message_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageElement.ProtoReflect.Descriptor instead.
func (*ImageElement) Descriptor() ([]byte, []int) {
	return file_idl_message_message_proto_rawDescGZIP(), []int{6}
}

func (x *ImageElement) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageElement) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImageElement) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImageElement) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ImageElement) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// VideoElement 视频消息内容
type VideoElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// url 视频URL
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// duration 视频时长（秒）
	Duration int32 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	// size 视频大小（字节数）
	Size int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// uuid 视频唯一标识符
	Uuid string `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *VideoElement) Reset() {
	*x = VideoElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_message_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoElement) ProtoMessage() {}

func (x *VideoElement) ProtoReflect() protoreflect.Message {
	mi := &file_idl_message_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoElement.ProtoReflect.Descriptor instead.
func (*VideoElement) Descriptor() ([]byte, []int) {
	return file_idl_message_message_proto_rawDescGZIP(), []int{7}
}

func (x *VideoElement) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *VideoElement) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *VideoElement) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *VideoElement) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// FileElement 文件消息内容
type FileElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// url 文件URL
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// file_name 文件名
	FileName string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// size 文件大小（字节数）
	Size int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// uuid 文件唯一标识符
	Uuid string `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *FileElement) Reset() {
	*x = FileElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_message_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileElement) ProtoMessage() {}

func (x *FileElement) ProtoReflect() protoreflect.Message {
	mi := &file_idl_message_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileElement.ProtoReflect.Descriptor instead.
func (*FileElement) Descriptor() ([]byte, []int) {
	return file_idl_message_message_proto_rawDescGZIP(), []int{8}
}

func (x *FileElement) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FileElement) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileElement) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileElement) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// AudioElement 音频消息内容
type AudioElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// url 音频URL
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// duration 音频时长（秒）
	Duration int32 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	// size 音频大小（字节数）
	Size int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// uuid 音频唯一标识符
	Uuid string `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *AudioElement) Reset() {
	*x = AudioElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_message_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioElement) ProtoMessage() {}

func (x *AudioElement) ProtoReflect() protoreflect.Message {
	mi := &file_idl_message_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioElement.ProtoReflect.Descriptor instead.
func (*AudioElement) Descriptor() ([]byte, []int) {
	return file_idl_message_message_proto_rawDescGZIP(), []int{9}
}

func (x *AudioElement) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AudioElement) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *AudioElement) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AudioElement) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// StickerElement 表情包消息内容
type StickerElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// sticker_id 表情包ID
	StickerId string `protobuf:"bytes,1,opt,name=sticker_id,json=stickerId,proto3" json:"sticker_id,omitempty"`
	// url 表情包URL
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// size 表情包大小（字节数）
	Size int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// uuid 表情包唯一标识符
	Uuid string `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *StickerElement) Reset() {
	*x = StickerElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_message_message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StickerElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerElement) ProtoMessage() {}

func (x *StickerElement) ProtoReflect() protoreflect.Message {
	mi := &file_idl_message_message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StickerElement.ProtoReflect.Descriptor instead.
func (*StickerElement) Descriptor() ([]byte, []int) {
	return file_idl_message_message_proto_rawDescGZIP(), []int{10}
}

func (x *StickerElement) GetStickerId() string {
	if x != nil {
		return x.StickerId
	}
	return ""
}

func (x *StickerElement) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *StickerElement) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StickerElement) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// MentionElement @提醒元素（独立的@元素，用于纯@消息或与其他元素组合）
type MentionElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// at_users @的用户ID列表
	AtUsers []string `protobuf:"bytes,1,rep,name=at_users,json=atUsers,proto3" json:"at_users,omitempty"`
	// at_all 是否@所有人（群聊时有效）
	AtAll bool `protobuf:"varint,2,opt,name=at_all,json=atAll,proto3" json:"at_all,omitempty"`
	// display_text 显示文本（可选，用于显示@的用户名，如"@张三 @李四"）
	DisplayText string `protobuf:"bytes,3,opt,name=display_text,json=displayText,proto3" json:"display_text,omitempty"`
}

func (x *MentionElement) Reset() {
	*x = MentionElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_message_message_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MentionElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentionElement) ProtoMessage() {}

func (x *MentionElement) ProtoReflect() protoreflect.Message {
	mi := &file_idl_message_message_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentionElement.ProtoReflect.Descriptor instead.
func (*MentionElement) Descriptor() ([]byte, []int) {
	return file_idl_message_message_proto_rawDescGZIP(), []int{11}
}

func (x *MentionElement) GetAtUsers() []string {
	if x != nil {
		return x.AtUsers
	}
	return nil
}

func (x *MentionElement) GetAtAll() bool {
	if x != nil {
		return x.AtAll
	}
	return false
}

func (x *MentionElement) GetDisplayText() string {
	if x != nil {
		return x.DisplayText
	}
	return ""
}

// CustomElement 自定义消息内容
type CustomElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// data 自定义数据（字节数组）
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CustomElement) Reset() {
	*x = CustomElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_message_message_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomElement) ProtoMessage() {}

func (x *CustomElement) ProtoReflect() protoreflect.Message {
	mi := &file_idl_message_message_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomElement.ProtoReflect.Descriptor instead.
func (*CustomElement) Descriptor() ([]byte, []int) {
	return file_idl_message_message_proto_rawDescGZIP(), []int{12}
}

func (x *CustomElement) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_idl_message_message_proto protoreflect.FileDescriptor

var file_idl_message_message_proto_rawDesc = []byte{
	0x0a, 0x19, 0x69, 0x64, 0x6c, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x5c, 0x0a, 0x0f, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0x6d, 0x0a, 0x10, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x70, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x27, 0x0a, 0x0e, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x22, 0xf7, 0x02, 0x0a, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x5f, 0x6d, 0x73,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x4d,
	0x73, 0x67, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x5f, 0x73, 0x65, 0x71, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x53, 0x65, 0x71,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x63,
	0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x52, 0x07, 0x6d, 0x73, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x6e,
	0x74, 0x5f, 0x74, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x74,
	0x54, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x0a,
	0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x15, 0x0a,
	0x06, 0x61, 0x74, 0x5f, 0x61, 0x6c, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61,
	0x74, 0x41, 0x6c, 0x6c, 0x22, 0xdf, 0x03, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x3e, 0x0a, 0x0c, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x54, 0x65, 0x78, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x12, 0x2d, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x05, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x12, 0x2d, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x43,
	0x12, 0x2d, 0x0a, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x12,
	0x33, 0x0a, 0x07, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x72, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x07, 0x73, 0x74, 0x69,
	0x63, 0x6b, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x4d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00,
	0x52, 0x07, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x06, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x48, 0x00, 0x52, 0x06, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x42, 0x09, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x21, 0x0a, 0x0b, 0x54, 0x65, 0x78, 0x74, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x76, 0x0a, 0x0c, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x22, 0x64, 0x0a, 0x0c, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x64, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x64, 0x0a,
	0x0c, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x22, 0x69, 0x0a, 0x0e, 0x53, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x65,
	0x0a, 0x0e, 0x4d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x61, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x61,
	0x74, 0x5f, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x74, 0x41,
	0x6c, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x54, 0x65, 0x78, 0x74, 0x22, 0x23, 0x0a, 0x0d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0xab, 0x01, 0x0a, 0x0b, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x45,
	0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x6b, 0x4e, 0x4f,
	0x57, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x4d, 0x45,
	0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50,
	0x5f, 0x43, 0x48, 0x41, 0x54, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19, 0x4d, 0x45, 0x53, 0x53, 0x41,
	0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x5f, 0x52, 0x45, 0x43,
	0x45, 0x49, 0x50, 0x54, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47,
	0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x43, 0x41, 0x4c, 0x4c, 0x10, 0x04, 0x12,
	0x17, 0x0a, 0x13, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x05, 0x2a, 0x8c, 0x02, 0x0a, 0x12, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1b, 0x0a, 0x17, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x4c, 0x45, 0x4d, 0x45,
	0x4e, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14,
	0x43, 0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x4c, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f,
	0x54, 0x45, 0x58, 0x54, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x4e,
	0x54, 0x5f, 0x45, 0x4c, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x10,
	0x02, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x4c, 0x45,
	0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14,
	0x43, 0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x4c, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f,
	0x46, 0x49, 0x4c, 0x45, 0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x4e,
	0x54, 0x5f, 0x45, 0x4c, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x41, 0x55, 0x44, 0x49, 0x4f, 0x10,
	0x05, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x4c, 0x45,
	0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x49, 0x43, 0x4b, 0x45, 0x52, 0x10, 0x06, 0x12, 0x1b,
	0x0a, 0x17, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x4c, 0x45, 0x4d, 0x45, 0x4e,
	0x54, 0x5f, 0x4d, 0x45, 0x4e, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x07, 0x12, 0x1a, 0x0a, 0x16, 0x43,
	0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x4c, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x43,
	0x55, 0x53, 0x54, 0x4f, 0x4d, 0x10, 0x08, 0x32, 0x54, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x53, 0x65, 0x6e,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x70, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a,
	0x0a, 0x2e, 0x2f, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_idl_message_message_proto_rawDescOnce sync.Once
	file_idl_message_message_proto_rawDescData = file_idl_message_message_proto_rawDesc
)

func file_idl_message_message_proto_rawDescGZIP() []byte {
	file_idl_message_message_proto_rawDescOnce.Do(func() {
		file_idl_message_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_message_message_proto_rawDescData)
	})
	return file_idl_message_message_proto_rawDescData
}

var file_idl_message_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_idl_message_message_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_idl_message_message_proto_goTypes = []interface{}{
	(MessageType)(0),         // 0: message.MessageType
	(MessageElementType)(0),  // 1: message.MessageElementType
	(*UpstreamRequest)(nil),  // 2: message.UpstreamRequest
	(*UpstreamResponse)(nil), // 3: message.UpstreamResponse
	(*UpstreamResult)(nil),   // 4: message.UpstreamResult
	(*Message)(nil),          // 5: message.Message
	(*MessageContent)(nil),   // 6: message.MessageContent
	(*TextElement)(nil),      // 7: message.TextElement
	(*ImageElement)(nil),     // 8: message.ImageElement
	(*VideoElement)(nil),     // 9: message.VideoElement
	(*FileElement)(nil),      // 10: message.FileElement
	(*AudioElement)(nil),     // 11: message.AudioElement
	(*StickerElement)(nil),   // 12: message.StickerElement
	(*MentionElement)(nil),   // 13: message.MentionElement
	(*CustomElement)(nil),    // 14: message.CustomElement
}
var file_idl_message_message_proto_depIdxs = []int32{
	0,  // 0: message.UpstreamRequest.msg_type:type_name -> message.MessageType
	4,  // 1: message.UpstreamResponse.data:type_name -> message.UpstreamResult
	0,  // 2: message.Message.msg_type:type_name -> message.MessageType
	6,  // 3: message.Message.msg_body:type_name -> message.MessageContent
	1,  // 4: message.MessageContent.element_type:type_name -> message.MessageElementType
	7,  // 5: message.MessageContent.text:type_name -> message.TextElement
	8,  // 6: message.MessageContent.image:type_name -> message.ImageElement
	9,  // 7: message.MessageContent.video:type_name -> message.VideoElement
	10, // 8: message.MessageContent.file_c:type_name -> message.FileElement
	11, // 9: message.MessageContent.audio:type_name -> message.AudioElement
	12, // 10: message.MessageContent.sticker:type_name -> message.StickerElement
	13, // 11: message.MessageContent.mention:type_name -> message.MentionElement
	14, // 12: message.MessageContent.custom:type_name -> message.CustomElement
	2,  // 13: message.MessageService.SendMessage:input_type -> message.UpstreamRequest
	3,  // 14: message.MessageService.SendMessage:output_type -> message.UpstreamResponse
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_idl_message_message_proto_init() }
func file_idl_message_message_proto_init() {
	if File_idl_message_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_message_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpstreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_message_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpstreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_message_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpstreamResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_message_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_message_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_message_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_message_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_message_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_message_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_message_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AudioElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_message_message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StickerElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_message_message_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MentionElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_message_message_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_idl_message_message_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*MessageContent_Text)(nil),
		(*MessageContent_Image)(nil),
		(*MessageContent_Video)(nil),
		(*MessageContent_FileC)(nil),
		(*MessageContent_Audio)(nil),
		(*MessageContent_Sticker)(nil),
		(*MessageContent_Mention)(nil),
		(*MessageContent_Custom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_message_message_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_message_message_proto_goTypes,
		DependencyIndexes: file_idl_message_message_proto_depIdxs,
		EnumInfos:         file_idl_message_message_proto_enumTypes,
		MessageInfos:      file_idl_message_message_proto_msgTypes,
	}.Build()
	File_idl_message_message_proto = out.File
	file_idl_message_message_proto_rawDesc = nil
	file_idl_message_message_proto_goTypes = nil
	file_idl_message_message_proto_depIdxs = nil
}
